language: scala
scala: 
    - 2.11.7
env:
- PLAY_VERSION=2.4.5
before_script:
- wget https://github.com/playframework/playframework/archive/${PLAY_VERSION}.zip
- unzip -q playframework-${PLAY_VERSION}.zip
script: playframework-${PLAY_VERSION}/play test
